import "./globals.css";
import { Inter } from "next/font/google";
import { ProviderRedux } from "@/store/ProviderRedux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { toastifyConfig } from "@/config/toastify.config";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Quizz Game",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="es">
            <body className={inter.className}>
                <div className="w-full min-h-screen font-bo">
                    <ToastContainer
                        {...toastifyConfig}
                        bodyClassName="font-bold flex justify-between items-center p-3"
                    />
                    <ProviderRedux>{children}</ProviderRedux>
                </div>
            </body>
        </html>
    );
}
